### ISSUE TITLE
null pointer on SupervisionGroup#terminate

### ISSUE THREAD

**Issue by paulwalker** [celluloid/celluloid#493] opened 2015-02-20 09:08 UTC
```ruby
 MySupervionGroup.pool(MyWorker, as: :worker_pool, size: 3)
 @supervisor = MySupervionGroup.run
```
```ruby
@supervisor.terminate
```
```bash
Terminating 3 actors...
Terminating task: type=:call, meta={:method_name=>:initialize}, status=:callwait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
Actor crashed!
NoMethodError: undefined method `delete' for nil:NilClass
	/Users/paul/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/celluloid-6a5c9cd57913/lib/celluloid/pool_manager.rb:130:in `__crash_handler__'
	/Users/paul/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/celluloid-6a5c9cd57913/lib/celluloid/cell.rb:15:in `block in call'
	/Users/paul/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/celluloid-6a5c9cd57913/lib/celluloid/cell.rb:71:in `block in task'
	/Users/paul/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/celluloid-6a5c9cd57913/lib/celluloid/actor.rb:357:in `block in task'
```

I'm not sure if you need more information, I don't believe I am doing anything out of the ordinary here. The actors in the pool continuously run upon initialization w/ periodic sleep. The init and termination of the SupervisionGroup happens in a daemon.

**Comment by ioquatix** [comment] 2015-02-20 09:15
According to a discussion with @tarcieri pools are buggy and you are best to avoid them if possible at the moment. They are scheduled for removal into their own gem for backwards compatibility and alternative implementation has been proposed: https://github.com/halorgium/celluloid-coordinator

**Comment by paulwalker** [comment] 2015-02-20 09:22
I was looking at that earlier and, while it looks like a good start to skeleton pool manager pattern, I didn't discern anything w/ actor crash mgmt, etc. But I'm just scratching the surface w/ this gem, so forgive my ignorance. Perhaps consider keeping this issue open, I'd be more than willing to test and give input on any updates. Thanks for the rapid response.

**Comment by paulwalker** [comment] 2015-02-20 09:27
Also, I don't see any issues beyond dirty log files after termination right now. Are there more serious issues with Pools/SuperVisionGroups? I need to decide whether to roll my own or just live with it before going to production...my use case is not that complex, the actors are self contained and read work synchronously off a queue by themselves. Thanks!

**Comment by ioquatix** [comment] 2015-02-20 09:29
@tarcieri is probably the best one to answer that.

**Comment by digitalextremist** [comment] 2015-08-06 13:29
This was resolved in the supervision refactor. Cannot reproduce any longer.

**Closed by digitalextremist** 2015-08-06 13:29 UTC
Labels: gem, pool, supervision
