### ISSUE TITLE
Registry not working for SupervisionGroups via supervise

### ISSUE THREAD

**Issue by jzahnd** [celluloid/celluloid#503] opened 2015-03-19 23:23 UTC
I have a situation where I am customizing the behavior and details of a SupervisionGroup. Using pools works just fine, but if I want to supervise only one actor, it appears as though the registry isn't working correctly. 
```
@supervisor = Celluloid::SupervisionGroup.run!

# works
@supervisor.pool(SocialData::Managers, as: :data_managers, size: 2, args: [data_name: "twitter"])
@supervisor[:data_managers].process 

# returns nil:NilClass (NoMethodError)
@supervisor.supervise(SocialData::Manager, as: :data_manager, args: [data_name: "twitter"])
@supervisor[:data_manager].process 
```
Based on everything I see, I should be able to use the above syntax to supervise one actor via a supervision group. The Celluloid::Actors approach also doesn't show the actor in the registry. Is this intentional? I am currently working with the latest from Master.

**Comment by digitalextremist** [comment] 2015-03-20 02:44
@jzahnd do you have a complete repro of this posted somewhere, either as a gist or repository? I'd be able to look at this if you do. Seems like you're almost there with a complete repro if there were just something to take in your arguments, and return a testable result to demonstrate the issue.

Just out of curiousity in the meantime, have you tried `supervise_as`, removing the `as:` parameter in the `args` Hash and giving `:data_manager` as the first parameter? At first glance, your usage should work, but I wonder if there's a difference between how `supervise` and `supervise_as` are behaving for some reason. Between knowing that and a repro we could probably address this quickly.

**Comment by jzahnd** [comment] 2015-03-20 03:32
@digitalextremist thanks for the quick response! I tried your suggestion with `supervise_as` and that seems to work. I will probably switch to that for now. 

It may just be a matter of documentation as the rdoc references appear to support the plain `supervise` method. But perhaps it wasn't intended to be used that way?

Anyway, I still put together an admittedly contrived example in this gist, including the supervise_as option, here: https://gist.github.com/jzahnd/e508d209c3c7a40ed681

**Comment by digitalextremist** [comment] 2015-03-20 03:35
@jzahnd awesome. Wow, your repro is pretty ninja :+1:

 I will look at this in a bit and either update the documentation or make a patch.

**Comment by digitalextremist** [comment] 2015-03-20 04:23
This is indeed a bug. `@name` is not being set, which is why I asked for `supervise_as` to be tried. Working on a patch.

**Comment by digitalextremist** [comment] 2015-03-20 04:27
I see the issue. Yes, this is a bug. Branching and patching. Good catch @jzahnd

**Comment by digitalextremist** [comment] 2015-03-20 04:32
@tarcieri this actually seems like a big glitch. I think it hasn't been noticed because we mostly use `supervise_as`. Patch nearly there.

**Comment by digitalextremist** [comment] 2015-03-20 04:34
@jzahnd also, be advised, `supervise_as` also does not work, it just does not fail.

**Comment by tarcieri** [comment] 2015-03-20 04:38
I think, a long time ago, I landed a patch that exposed all these methods in weird ways.

The SupervisorGroup API was intended to be a class-level DSL for describing supervisor classes.

Using it with instance methods like this is dangerously racy, and worse the state is potentially lost if the supervisor crashes.

Supervisors could use an overhaul in general.

**Comment by jzahnd** [comment] 2015-03-20 04:38
Well, I'm glad I ran into it then. I ended up jumping into the code documentation as opposed to examples, so that might explain it. I am an expert in breaking things :stuck_out_tongue:.

I did just run into the supervise_as you are describing in your last comment @digitalextremist. I saw there was no error and assumed it was fine, but should have checked the actual execution.

**Comment by jzahnd** [comment] 2015-03-20 04:42
agreed @tarcieri. I am using defined groups in most scenarios but found the API helpful for some odd usecases. I will be using this with care though.

Thanks again @digitalextremist for looking into it.

**Comment by digitalextremist** [comment] 2015-03-20 04:42
@tarcieri I caught the code smell, but I think my patch handles the issue for the time being while we overhaul supervisors. It seems like this was a theory mistake -- `args` was being passed in like this:

```
"args" => {
    "args" => []
}
```

So I flattened the `options` passed in, using `pool` as the model for correct behavior, then merging in the special parameters per method.

**Comment by digitalextremist** [comment] 2015-03-20 04:44
Resolved -- thanks again @jzahnd for the repro and the initial report.

**Comment by paulwalker** [comment] 2015-03-23 01:28
This "fix" cause a bug in autostart:

```
E, [2015-03-22T18:18:49.832823 #50388] ERROR -- : Actor crashed!
NoMethodError: undefined method `merge' for #<IO:<STDERR>>
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/supervision_group.rb:77:in `supervise_as'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/calls.rb:26:in `public_send'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/calls.rb:26:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/calls.rb:79:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/cell.rb:60:in `block in invoke'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/cell.rb:71:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:357:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/tasks.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
D, [2015-03-22T18:18:49.833080 #50388] DEBUG -- : Terminating task: type=:call, meta={:method_name=>:initialize}, status=:callwait
	Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
task was terminated
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/tasks/task_fiber.rb:33:in `terminate'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:345:in `each'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:345:in `cleanup'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:329:in `shutdown'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:321:in `handle_crash'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:166:in `rescue in run'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:148:in `run'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor.rb:130:in `block in start'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/internal_pool.rb:129:in `call'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/internal_pool.rb:129:in `block in create'
(celluloid):0:in `remote procedure call'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/calls.rb:108:in `value'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid.rb:171:in `new'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/supervisor.rb:18:in `supervise_as'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid.rb:196:in `supervise_as'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor_system.rb:16:in `block in start'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor_system.rb:24:in `within'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/actor_system.rb:14:in `start'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid.rb:131:in `start'
/usr/local/lib/ruby/gems/2.2.0/bundler/gems/celluloid-eb5f36253d4f/lib/celluloid/autostart.rb:3:in `<top (required)>'
```

The call in actor_system.rb `Celluloid::IncidentReporter.supervise_as :default_incident_reporter, STDERR`

STDERR is getting passed in to the opts = {} argument, which cannot be merged as a hash.

**Comment by digitalextremist** [comment] 2015-03-24 02:19
Will resolve this tonight.

**Comment by digitalextremist** [comment] 2015-03-24 02:20
@paulwalker .. was this after `celluloid/autostart` itself, without any particular code of yours invoked, or was there also code invoked?

**Comment by paulwalker** [comment] 2015-03-24 02:23
I was getting it trying to start sidekiq from the command line. Sorry, I cut that part out, but it was occuring in sidekiq cli after `require 'celluloid/autostart'`

**Comment by digitalextremist** [comment] 2015-03-24 03:42
I can reproduce the error with `require 'celluloid/autostart'` so far.

**Comment by digitalextremist** [comment] 2015-03-24 07:31
@paulwalker please retest now that it's merged in.

**Closed** 2015-03-24 07:30 UTC
