### ISSUE TITLE
Celluloid::TimeoutError: receive timeout exceeded

### ISSUE THREAD

**Issue by blanchma** [celluloid/celluloid#475] opened 2014-11-13 20:31 UTC
Running a job inside a loop. The loop fires async jobs. Some jobs returns:

Celluloid::TimeoutError: receive timeout exceeded
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/mailbox.rb:80:in `receive'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/calls.rb:97:in `wait'
org/jruby/RubyKernel.java:1501:in `loop'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/calls.rb:96:in `wait'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid.rb:116:in `suspend'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/calls.rb:88:in `response'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
/Users/blanchma/.rvm/gems/jruby-1.7.13@applicationservice/gems/celluloid-0.16.0/lib/celluloid.rb:169:in `new'

Environment: 
jruby-1.7.13
celluloid (0.16.0)

**Comment by digitalextremist** [comment] 2015-03-28 08:59
@blanchma can you please post the repro you're talking about, so I can help here?

**Comment by basgys-cw** [comment] 2015-03-28 09:43
@digitalextremist Unfortunately I don't work on this project anymore, so you can discard my comment.

**Comment by digitalextremist** [comment] 2015-03-28 09:45
@basgys-cw can you unsubscribe from the issue so I can just leave the issue intact, and people can see that you're no longer participating by virtue of your comment to that effect?

**Comment by digitalextremist** [comment] 2015-04-08 17:59
I am now having this issue in jruby `1.7.19`. Will address in `0.17.0`

**Comment by digitalextremist** [comment] 2015-04-08 18:00
Duplicate of #464

**Closed by digitalextremist** 2015-04-08 18:00 UTC
